name: CMake on a single platform

on:
  push:
    branches: [ "main", "feat/**", "dev/**", "ci/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Apt LLVM
      run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo apt-get purge -y "clang-[0-9]*" "llvm-[0-9]*" "lldb-[0-9]*"
          sudo apt-get autoremove -y
          sudo ./llvm.sh 20 all
          sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
          sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100

    - name: Setup Environment
      run: | 
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends libglfw3 libglfw3-dev libx11-dev libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libxext-dev libxfixes-dev libwayland-dev libxkbcommon-dev
      shell: bash

    - name: Configure CMake
      run: make configure_release

    - name: Build
      run: make build_release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: release_linux
        path: ./build/DemoCrocobyGraph

  build_windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Configure CMake
      run: make configure_release

    - name: Build
      run: make build_release

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v7.0.1
      with:
        name: release_windows
        path: ./build/DemoCrocobyGraph.exe
